Add a line on contribute doc to ask author publishing Microsoft authorized template to azure samples browser
Azure/awesome-azd pull request #404
Opened 2024-06-18 23:31 UTC by hemarina

The manual test team are constantly tracking and creating PRs to publish msft authorized templates to azure samples browser. We should consider letting the author decides if they want to add their templates on azure samples browser.

2024-06-19 03:21 UTC, kristenwomack requested changes
I suggested a change, and I have an open question on a point I don't understand. I'm supportive of the spirit of this change. We'll want to also look at this in the lens of the azd artifacts in the template standardization effort.

2024-06-19 03:21 UTC, kristenwomack commented on website/docs/contribute.md
> +2. If the template is microsoft authorized, we encourage to [publish the template to azure samples browsers](https://review.learn.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch
```suggestion
2. If the template is Microsoft authorized, we encourage to [publish the template to Azure samples browsers](https://review.learn.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch=main). 
```

2024-06-19 03:21 UTC, kristenwomack commented on website/docs/contribute.md
> +2. If the template is microsoft authorized, we encourage to [publish the template to azure samples browsers](https://review.learn.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch
What does Microsoft authorized mean? Is this one that is authored by a Microsoft employee? Or part of a Microsoft curated collection of templates?

2024-06-19 03:21 UTC, kristenwomack commented on website/docs/contribute.md
> +4. If possible, add a link to the PR in your repo where you made your app `azd` compatible to the PR description. This will help us provide feedback on your template and speed up the review process.
I like this.

2024-06-19 19:40 UTC, gkulin commented on website/docs/contribute.md
> +2. If the template is microsoft authorized, we encourage to [publish the template to azure samples browsers](https://review.learn.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch
```suggestion
2. If the template is Microsoft-authored, we encourage you to also [publish it to learn.microsoft.com/samples](https://review.learn.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch=main). 
```

2024-06-20 00:09 UTC, hemarina commented on website/docs/contribute.md
> +2. If the template is microsoft authorized, we encourage to [publish the template to azure samples browsers](https://review.learn.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch
The template is hosted under Microsoft org like Azure-Samples, Azure, dotnet, etc. and maintained by Microsoft teams or employees.

2024-06-20 03:01 UTC, kristenwomack approved these changes
LGTM

2024-06-20 23:02 UTC, gkulin approved these changes

2024-06-20 23:03 UTC, merged